/** Generated by the default template from graphql-java-generator */
package cn.zy.client.util;

import java.io.IOException;
import java.util.List;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.graphql_java_generator.client.response.AbstractCustomJacksonDeserializer;
import com.graphql_java_generator.customscalars.GraphQLScalarTypeDate;

import graphql.schema.GraphQLScalarType;

/**
 * This class is a standard Deserializer for Jackson. It uses the {@link GraphQLScalarType} that is implemented by the project for this scalar
 */
@SuppressWarnings("unused")
public class CustomJacksonDeserializers {
	
	public static class ListArtifactRepository extends AbstractCustomJacksonDeserializer<List<cn.zy.client.ArtifactRepository>> {
		private static final long serialVersionUID = 1L;
		public ListArtifactRepository() {
			super(
				null,
true,
				cn.zy.client.ArtifactRepository.class,
				null
			);
		}
	}

	public static class List__Directive extends AbstractCustomJacksonDeserializer<List<cn.zy.client.__Directive>> {
		private static final long serialVersionUID = 1L;
		public List__Directive() {
			super(
				null,
true,
				cn.zy.client.__Directive.class,
				null
			);
		}
	}

	public static class List__InputValue extends AbstractCustomJacksonDeserializer<List<cn.zy.client.__InputValue>> {
		private static final long serialVersionUID = 1L;
		public List__InputValue() {
			super(
				null,
true,
				cn.zy.client.__InputValue.class,
				null
			);
		}
	}

	public static class List__Type extends AbstractCustomJacksonDeserializer<List<cn.zy.client.__Type>> {
		private static final long serialVersionUID = 1L;
		public List__Type() {
			super(
				null,
true,
				cn.zy.client.__Type.class,
				null
			);
		}
	}

	public static class List__EnumValue extends AbstractCustomJacksonDeserializer<List<cn.zy.client.__EnumValue>> {
		private static final long serialVersionUID = 1L;
		public List__EnumValue() {
			super(
				null,
true,
				cn.zy.client.__EnumValue.class,
				null
			);
		}
	}

	public static class List__DirectiveLocation extends AbstractCustomJacksonDeserializer<List<cn.zy.client.__DirectiveLocation>> {
		private static final long serialVersionUID = 1L;
		public List__DirectiveLocation() {
			super(
				null,
true,
				cn.zy.client.__DirectiveLocation.class,
				null
			);
		}
	}

	public static class List__Field extends AbstractCustomJacksonDeserializer<List<cn.zy.client.__Field>> {
		private static final long serialVersionUID = 1L;
		public List__Field() {
			super(
				null,
true,
				cn.zy.client.__Field.class,
				null
			);
		}
	}

}
