/** Generated by the default template from graphql-java-generator */
package cn.zy.client.util;

import java.util.List;

import com.graphql_java_generator.client.request.AbstractCustomJacksonSerializer;

import graphql.schema.GraphQLScalarType;

/**
 * This class is a standard Deserializer for Jackson. It uses the {@link GraphQLScalarType} that is implemented by the project for this scalar
 */
@SuppressWarnings("unused")
public class CustomJacksonSerializers {
	
}
