/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("Acceleration")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class Acceleration 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public Acceleration(){
		// No action
	}

	@JsonProperty("from0To100Kmh")
	@GraphQLNonScalar(fieldName = "from0To100Kmh", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To100Kmh;


	@JsonProperty("from0To100KmhLaunchControl")
	@GraphQLNonScalar(fieldName = "from0To100KmhLaunchControl", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To100KmhLaunchControl;


	@JsonProperty("from0To100KmhSportChrono")
	@GraphQLNonScalar(fieldName = "from0To100KmhSportChrono", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To100KmhSportChrono;


	@JsonProperty("from0To160Kmh")
	@GraphQLNonScalar(fieldName = "from0To160Kmh", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To160Kmh;


	@JsonProperty("from0To160KmhLaunchControl")
	@GraphQLNonScalar(fieldName = "from0To160KmhLaunchControl", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To160KmhLaunchControl;


	@JsonProperty("from0To160KmhSportChrono")
	@GraphQLNonScalar(fieldName = "from0To160KmhSportChrono", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To160KmhSportChrono;


	@JsonProperty("from0To200Kmh")
	@GraphQLNonScalar(fieldName = "from0To200Kmh", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To200Kmh;


	@JsonProperty("from0To200KmhLaunchControl")
	@GraphQLNonScalar(fieldName = "from0To200KmhLaunchControl", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To200KmhLaunchControl;


	@JsonProperty("from0To200KmhSportChrono")
	@GraphQLNonScalar(fieldName = "from0To200KmhSportChrono", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To200KmhSportChrono;


	@JsonProperty("from0To300Kmh")
	@GraphQLNonScalar(fieldName = "from0To300Kmh", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To300Kmh;


	@JsonProperty("from0To60Mph")
	@GraphQLNonScalar(fieldName = "from0To60Mph", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To60Mph;


	@JsonProperty("from0To60MphLaunchControl")
	@GraphQLNonScalar(fieldName = "from0To60MphLaunchControl", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To60MphLaunchControl;


	@JsonProperty("from0To60MphSportChrono")
	@GraphQLNonScalar(fieldName = "from0To60MphSportChrono", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from0To60MphSportChrono;


	@JsonProperty("from80To120KmhElasticity5thGear")
	@GraphQLNonScalar(fieldName = "from80To120KmhElasticity5thGear", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from80To120KmhElasticity5thGear;


	@JsonProperty("from80To120KmhInGear")
	@GraphQLNonScalar(fieldName = "from80To120KmhInGear", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from80To120KmhInGear;


	@JsonProperty("from80To120KmhInGearSportChrono")
	@GraphQLNonScalar(fieldName = "from80To120KmhInGearSportChrono", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem from80To120KmhInGearSportChrono;


	@JsonProperty("quarterMile")
	@GraphQLNonScalar(fieldName = "quarterMile", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem quarterMile;


	@JsonProperty("quarterMileSportChrono")
	@GraphQLNonScalar(fieldName = "quarterMileSportChrono", graphQLTypeSimpleName = "AccelerationTechnicalDataItem", javaClass = AccelerationTechnicalDataItem.class)
	AccelerationTechnicalDataItem quarterMileSportChrono;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setFrom0To100Kmh(AccelerationTechnicalDataItem from0To100Kmh) {
		this.from0To100Kmh = from0To100Kmh;
	}

	public AccelerationTechnicalDataItem getFrom0To100Kmh() {
		return from0To100Kmh;
	}
		

	public void setFrom0To100KmhLaunchControl(AccelerationTechnicalDataItem from0To100KmhLaunchControl) {
		this.from0To100KmhLaunchControl = from0To100KmhLaunchControl;
	}

	public AccelerationTechnicalDataItem getFrom0To100KmhLaunchControl() {
		return from0To100KmhLaunchControl;
	}
		

	public void setFrom0To100KmhSportChrono(AccelerationTechnicalDataItem from0To100KmhSportChrono) {
		this.from0To100KmhSportChrono = from0To100KmhSportChrono;
	}

	public AccelerationTechnicalDataItem getFrom0To100KmhSportChrono() {
		return from0To100KmhSportChrono;
	}
		

	public void setFrom0To160Kmh(AccelerationTechnicalDataItem from0To160Kmh) {
		this.from0To160Kmh = from0To160Kmh;
	}

	public AccelerationTechnicalDataItem getFrom0To160Kmh() {
		return from0To160Kmh;
	}
		

	public void setFrom0To160KmhLaunchControl(AccelerationTechnicalDataItem from0To160KmhLaunchControl) {
		this.from0To160KmhLaunchControl = from0To160KmhLaunchControl;
	}

	public AccelerationTechnicalDataItem getFrom0To160KmhLaunchControl() {
		return from0To160KmhLaunchControl;
	}
		

	public void setFrom0To160KmhSportChrono(AccelerationTechnicalDataItem from0To160KmhSportChrono) {
		this.from0To160KmhSportChrono = from0To160KmhSportChrono;
	}

	public AccelerationTechnicalDataItem getFrom0To160KmhSportChrono() {
		return from0To160KmhSportChrono;
	}
		

	public void setFrom0To200Kmh(AccelerationTechnicalDataItem from0To200Kmh) {
		this.from0To200Kmh = from0To200Kmh;
	}

	public AccelerationTechnicalDataItem getFrom0To200Kmh() {
		return from0To200Kmh;
	}
		

	public void setFrom0To200KmhLaunchControl(AccelerationTechnicalDataItem from0To200KmhLaunchControl) {
		this.from0To200KmhLaunchControl = from0To200KmhLaunchControl;
	}

	public AccelerationTechnicalDataItem getFrom0To200KmhLaunchControl() {
		return from0To200KmhLaunchControl;
	}
		

	public void setFrom0To200KmhSportChrono(AccelerationTechnicalDataItem from0To200KmhSportChrono) {
		this.from0To200KmhSportChrono = from0To200KmhSportChrono;
	}

	public AccelerationTechnicalDataItem getFrom0To200KmhSportChrono() {
		return from0To200KmhSportChrono;
	}
		

	public void setFrom0To300Kmh(AccelerationTechnicalDataItem from0To300Kmh) {
		this.from0To300Kmh = from0To300Kmh;
	}

	public AccelerationTechnicalDataItem getFrom0To300Kmh() {
		return from0To300Kmh;
	}
		

	public void setFrom0To60Mph(AccelerationTechnicalDataItem from0To60Mph) {
		this.from0To60Mph = from0To60Mph;
	}

	public AccelerationTechnicalDataItem getFrom0To60Mph() {
		return from0To60Mph;
	}
		

	public void setFrom0To60MphLaunchControl(AccelerationTechnicalDataItem from0To60MphLaunchControl) {
		this.from0To60MphLaunchControl = from0To60MphLaunchControl;
	}

	public AccelerationTechnicalDataItem getFrom0To60MphLaunchControl() {
		return from0To60MphLaunchControl;
	}
		

	public void setFrom0To60MphSportChrono(AccelerationTechnicalDataItem from0To60MphSportChrono) {
		this.from0To60MphSportChrono = from0To60MphSportChrono;
	}

	public AccelerationTechnicalDataItem getFrom0To60MphSportChrono() {
		return from0To60MphSportChrono;
	}
		

	public void setFrom80To120KmhElasticity5thGear(AccelerationTechnicalDataItem from80To120KmhElasticity5thGear) {
		this.from80To120KmhElasticity5thGear = from80To120KmhElasticity5thGear;
	}

	public AccelerationTechnicalDataItem getFrom80To120KmhElasticity5thGear() {
		return from80To120KmhElasticity5thGear;
	}
		

	public void setFrom80To120KmhInGear(AccelerationTechnicalDataItem from80To120KmhInGear) {
		this.from80To120KmhInGear = from80To120KmhInGear;
	}

	public AccelerationTechnicalDataItem getFrom80To120KmhInGear() {
		return from80To120KmhInGear;
	}
		

	public void setFrom80To120KmhInGearSportChrono(AccelerationTechnicalDataItem from80To120KmhInGearSportChrono) {
		this.from80To120KmhInGearSportChrono = from80To120KmhInGearSportChrono;
	}

	public AccelerationTechnicalDataItem getFrom80To120KmhInGearSportChrono() {
		return from80To120KmhInGearSportChrono;
	}
		

	public void setQuarterMile(AccelerationTechnicalDataItem quarterMile) {
		this.quarterMile = quarterMile;
	}

	public AccelerationTechnicalDataItem getQuarterMile() {
		return quarterMile;
	}
		

	public void setQuarterMileSportChrono(AccelerationTechnicalDataItem quarterMileSportChrono) {
		this.quarterMileSportChrono = quarterMileSportChrono;
	}

	public AccelerationTechnicalDataItem getQuarterMileSportChrono() {
		return quarterMileSportChrono;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "Acceleration {"
				+ "from0To100Kmh: " + from0To100Kmh
				+ ", "
				+ "from0To100KmhLaunchControl: " + from0To100KmhLaunchControl
				+ ", "
				+ "from0To100KmhSportChrono: " + from0To100KmhSportChrono
				+ ", "
				+ "from0To160Kmh: " + from0To160Kmh
				+ ", "
				+ "from0To160KmhLaunchControl: " + from0To160KmhLaunchControl
				+ ", "
				+ "from0To160KmhSportChrono: " + from0To160KmhSportChrono
				+ ", "
				+ "from0To200Kmh: " + from0To200Kmh
				+ ", "
				+ "from0To200KmhLaunchControl: " + from0To200KmhLaunchControl
				+ ", "
				+ "from0To200KmhSportChrono: " + from0To200KmhSportChrono
				+ ", "
				+ "from0To300Kmh: " + from0To300Kmh
				+ ", "
				+ "from0To60Mph: " + from0To60Mph
				+ ", "
				+ "from0To60MphLaunchControl: " + from0To60MphLaunchControl
				+ ", "
				+ "from0To60MphSportChrono: " + from0To60MphSportChrono
				+ ", "
				+ "from80To120KmhElasticity5thGear: " + from80To120KmhElasticity5thGear
				+ ", "
				+ "from80To120KmhInGear: " + from80To120KmhInGear
				+ ", "
				+ "from80To120KmhInGearSportChrono: " + from80To120KmhInGearSportChrono
				+ ", "
				+ "quarterMile: " + quarterMile
				+ ", "
				+ "quarterMileSportChrono: " + quarterMileSportChrono
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private AccelerationTechnicalDataItem from0To100Kmh;
		private AccelerationTechnicalDataItem from0To100KmhLaunchControl;
		private AccelerationTechnicalDataItem from0To100KmhSportChrono;
		private AccelerationTechnicalDataItem from0To160Kmh;
		private AccelerationTechnicalDataItem from0To160KmhLaunchControl;
		private AccelerationTechnicalDataItem from0To160KmhSportChrono;
		private AccelerationTechnicalDataItem from0To200Kmh;
		private AccelerationTechnicalDataItem from0To200KmhLaunchControl;
		private AccelerationTechnicalDataItem from0To200KmhSportChrono;
		private AccelerationTechnicalDataItem from0To300Kmh;
		private AccelerationTechnicalDataItem from0To60Mph;
		private AccelerationTechnicalDataItem from0To60MphLaunchControl;
		private AccelerationTechnicalDataItem from0To60MphSportChrono;
		private AccelerationTechnicalDataItem from80To120KmhElasticity5thGear;
		private AccelerationTechnicalDataItem from80To120KmhInGear;
		private AccelerationTechnicalDataItem from80To120KmhInGearSportChrono;
		private AccelerationTechnicalDataItem quarterMile;
		private AccelerationTechnicalDataItem quarterMileSportChrono;

		public Builder withFrom0To100Kmh(AccelerationTechnicalDataItem from0To100Kmh) {
			this.from0To100Kmh = from0To100Kmh;
			return this;
		}
		public Builder withFrom0To100KmhLaunchControl(AccelerationTechnicalDataItem from0To100KmhLaunchControl) {
			this.from0To100KmhLaunchControl = from0To100KmhLaunchControl;
			return this;
		}
		public Builder withFrom0To100KmhSportChrono(AccelerationTechnicalDataItem from0To100KmhSportChrono) {
			this.from0To100KmhSportChrono = from0To100KmhSportChrono;
			return this;
		}
		public Builder withFrom0To160Kmh(AccelerationTechnicalDataItem from0To160Kmh) {
			this.from0To160Kmh = from0To160Kmh;
			return this;
		}
		public Builder withFrom0To160KmhLaunchControl(AccelerationTechnicalDataItem from0To160KmhLaunchControl) {
			this.from0To160KmhLaunchControl = from0To160KmhLaunchControl;
			return this;
		}
		public Builder withFrom0To160KmhSportChrono(AccelerationTechnicalDataItem from0To160KmhSportChrono) {
			this.from0To160KmhSportChrono = from0To160KmhSportChrono;
			return this;
		}
		public Builder withFrom0To200Kmh(AccelerationTechnicalDataItem from0To200Kmh) {
			this.from0To200Kmh = from0To200Kmh;
			return this;
		}
		public Builder withFrom0To200KmhLaunchControl(AccelerationTechnicalDataItem from0To200KmhLaunchControl) {
			this.from0To200KmhLaunchControl = from0To200KmhLaunchControl;
			return this;
		}
		public Builder withFrom0To200KmhSportChrono(AccelerationTechnicalDataItem from0To200KmhSportChrono) {
			this.from0To200KmhSportChrono = from0To200KmhSportChrono;
			return this;
		}
		public Builder withFrom0To300Kmh(AccelerationTechnicalDataItem from0To300Kmh) {
			this.from0To300Kmh = from0To300Kmh;
			return this;
		}
		public Builder withFrom0To60Mph(AccelerationTechnicalDataItem from0To60Mph) {
			this.from0To60Mph = from0To60Mph;
			return this;
		}
		public Builder withFrom0To60MphLaunchControl(AccelerationTechnicalDataItem from0To60MphLaunchControl) {
			this.from0To60MphLaunchControl = from0To60MphLaunchControl;
			return this;
		}
		public Builder withFrom0To60MphSportChrono(AccelerationTechnicalDataItem from0To60MphSportChrono) {
			this.from0To60MphSportChrono = from0To60MphSportChrono;
			return this;
		}
		public Builder withFrom80To120KmhElasticity5thGear(AccelerationTechnicalDataItem from80To120KmhElasticity5thGear) {
			this.from80To120KmhElasticity5thGear = from80To120KmhElasticity5thGear;
			return this;
		}
		public Builder withFrom80To120KmhInGear(AccelerationTechnicalDataItem from80To120KmhInGear) {
			this.from80To120KmhInGear = from80To120KmhInGear;
			return this;
		}
		public Builder withFrom80To120KmhInGearSportChrono(AccelerationTechnicalDataItem from80To120KmhInGearSportChrono) {
			this.from80To120KmhInGearSportChrono = from80To120KmhInGearSportChrono;
			return this;
		}
		public Builder withQuarterMile(AccelerationTechnicalDataItem quarterMile) {
			this.quarterMile = quarterMile;
			return this;
		}
		public Builder withQuarterMileSportChrono(AccelerationTechnicalDataItem quarterMileSportChrono) {
			this.quarterMileSportChrono = quarterMileSportChrono;
			return this;
		}

		public Acceleration build() {
			Acceleration _object = new Acceleration();
			_object.setFrom0To100Kmh(from0To100Kmh);
			_object.setFrom0To100KmhLaunchControl(from0To100KmhLaunchControl);
			_object.setFrom0To100KmhSportChrono(from0To100KmhSportChrono);
			_object.setFrom0To160Kmh(from0To160Kmh);
			_object.setFrom0To160KmhLaunchControl(from0To160KmhLaunchControl);
			_object.setFrom0To160KmhSportChrono(from0To160KmhSportChrono);
			_object.setFrom0To200Kmh(from0To200Kmh);
			_object.setFrom0To200KmhLaunchControl(from0To200KmhLaunchControl);
			_object.setFrom0To200KmhSportChrono(from0To200KmhSportChrono);
			_object.setFrom0To300Kmh(from0To300Kmh);
			_object.setFrom0To60Mph(from0To60Mph);
			_object.setFrom0To60MphLaunchControl(from0To60MphLaunchControl);
			_object.setFrom0To60MphSportChrono(from0To60MphSportChrono);
			_object.setFrom80To120KmhElasticity5thGear(from80To120KmhElasticity5thGear);
			_object.setFrom80To120KmhInGear(from80To120KmhInGear);
			_object.setFrom80To120KmhInGearSportChrono(from80To120KmhInGearSportChrono);
			_object.setQuarterMile(quarterMile);
			_object.setQuarterMileSportChrono(quarterMileSportChrono);
			_object.set__typename("Acceleration");
			return _object;
		}
	}
}
