/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import com.graphql_java_generator.annotation.GraphQLEnumType;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLEnumType("CritAir")
@SuppressWarnings("unused")
public enum CritAir {
GREEN, VIOLET_1, YELLOW_2, ORANGE_3, RED_4, GREY_5, UNCLASSIFIED;
}
