/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import com.graphql_java_generator.annotation.GraphQLEnumType;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLEnumType("EquipmentCategory")
@SuppressWarnings("unused")
public enum EquipmentCategory {
PACKAGES, EXTERIOR_COLOR, FOILS, INTERIOR_COLOR, EXTERIOR, TRANSMISSION_CHASSIS, WHEELS, INTERIOR, INTERIOR_BLACK, INTERIOR_LEATHER, INTERIOR_ALCANTARA, INTERIOR_RACE_TEX, INTERIOR_WOOD, INTERIOR_CARBON, INTERIOR_ALUMINIUM, AUDIO_COMMUNICATION, E_MOBILITY, FACTORY_COLLECTION, PCCD_OTHERS, STEERING_CODES, TEST_VEHICLES, Z_OPTIONS_INTERNAL, COLOUR_LEATHER_STITCHINGS, LIGHTS_VISION, COMFORT_ASSISTANCE, PORSCHE_APPROVED, OTHERS;
}
