/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;
import java.util.List;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("EquipmentChangeInput")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class EquipmentChangeInput 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public EquipmentChangeInput(){
		// No action
	}

	@JsonProperty("addCustomEquipment")
	@GraphQLNonScalar(fieldName = "addCustomEquipment", graphQLTypeSimpleName = "CustomEquipmentModificationInput", javaClass = CustomEquipmentModificationInput.class)
	List<CustomEquipmentModificationInput> addCustomEquipment;


	@JsonProperty("removeCatalogEquipmentByOptionCodes")
	@GraphQLScalar(fieldName = "removeCatalogEquipmentByOptionCodes", graphQLTypeSimpleName = "String", javaClass = String.class)
	List<String> removeCatalogEquipmentByOptionCodes;


	@JsonProperty("removeCustomEquipmentByNames")
	@GraphQLScalar(fieldName = "removeCustomEquipmentByNames", graphQLTypeSimpleName = "String", javaClass = String.class)
	List<String> removeCustomEquipmentByNames;


	@JsonProperty("setManualWheels")
	@GraphQLNonScalar(fieldName = "setManualWheels", graphQLTypeSimpleName = "ManualWheelsModificationInput", javaClass = ManualWheelsModificationInput.class)
	ManualWheelsModificationInput setManualWheels;


	@JsonProperty("setSelectedWheels")
	@GraphQLNonScalar(fieldName = "setSelectedWheels", graphQLTypeSimpleName = "SelectedOptionCodeModificationInput", javaClass = SelectedOptionCodeModificationInput.class)
	SelectedOptionCodeModificationInput setSelectedWheels;



	public void setAddCustomEquipment(List<CustomEquipmentModificationInput> addCustomEquipment) {
		this.addCustomEquipment = addCustomEquipment;
	}

	public List<CustomEquipmentModificationInput> getAddCustomEquipment() {
		return addCustomEquipment;
	}
		

	public void setRemoveCatalogEquipmentByOptionCodes(List<String> removeCatalogEquipmentByOptionCodes) {
		this.removeCatalogEquipmentByOptionCodes = removeCatalogEquipmentByOptionCodes;
	}

	public List<String> getRemoveCatalogEquipmentByOptionCodes() {
		return removeCatalogEquipmentByOptionCodes;
	}
		

	public void setRemoveCustomEquipmentByNames(List<String> removeCustomEquipmentByNames) {
		this.removeCustomEquipmentByNames = removeCustomEquipmentByNames;
	}

	public List<String> getRemoveCustomEquipmentByNames() {
		return removeCustomEquipmentByNames;
	}
		

	public void setSetManualWheels(ManualWheelsModificationInput setManualWheels) {
		this.setManualWheels = setManualWheels;
	}

	public ManualWheelsModificationInput getSetManualWheels() {
		return setManualWheels;
	}
		

	public void setSetSelectedWheels(SelectedOptionCodeModificationInput setSelectedWheels) {
		this.setSelectedWheels = setSelectedWheels;
	}

	public SelectedOptionCodeModificationInput getSetSelectedWheels() {
		return setSelectedWheels;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "EquipmentChangeInput {"
				+ "addCustomEquipment: " + addCustomEquipment
				+ ", "
				+ "removeCatalogEquipmentByOptionCodes: " + removeCatalogEquipmentByOptionCodes
				+ ", "
				+ "removeCustomEquipmentByNames: " + removeCustomEquipmentByNames
				+ ", "
				+ "setManualWheels: " + setManualWheels
				+ ", "
				+ "setSelectedWheels: " + setSelectedWheels
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private List<CustomEquipmentModificationInput> addCustomEquipment;
		private List<String> removeCatalogEquipmentByOptionCodes;
		private List<String> removeCustomEquipmentByNames;
		private ManualWheelsModificationInput setManualWheels;
		private SelectedOptionCodeModificationInput setSelectedWheels;

		public Builder withAddCustomEquipment(List<CustomEquipmentModificationInput> addCustomEquipment) {
			this.addCustomEquipment = addCustomEquipment;
			return this;
		}
		public Builder withRemoveCatalogEquipmentByOptionCodes(List<String> removeCatalogEquipmentByOptionCodes) {
			this.removeCatalogEquipmentByOptionCodes = removeCatalogEquipmentByOptionCodes;
			return this;
		}
		public Builder withRemoveCustomEquipmentByNames(List<String> removeCustomEquipmentByNames) {
			this.removeCustomEquipmentByNames = removeCustomEquipmentByNames;
			return this;
		}
		public Builder withSetManualWheels(ManualWheelsModificationInput setManualWheels) {
			this.setManualWheels = setManualWheels;
			return this;
		}
		public Builder withSetSelectedWheels(SelectedOptionCodeModificationInput setSelectedWheels) {
			this.setSelectedWheels = setSelectedWheels;
			return this;
		}

		public EquipmentChangeInput build() {
			EquipmentChangeInput _object = new EquipmentChangeInput();
			_object.setAddCustomEquipment(addCustomEquipment);
			_object.setRemoveCatalogEquipmentByOptionCodes(removeCatalogEquipmentByOptionCodes);
			_object.setRemoveCustomEquipmentByNames(removeCustomEquipmentByNames);
			_object.setSetManualWheels(setManualWheels);
			_object.setSetSelectedWheels(setSelectedWheels);
			return _object;
		}
	}
}
