/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("EquipmentMutations")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class EquipmentMutations 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public EquipmentMutations(){
		// No action
	}

	@JsonProperty("addCustomEquipment")
	@GraphQLInputParameters(names = {"inventoryId", "customEquipment"}, types = {"String", "CustomEquipmentModificationInput"}, mandatories = {true, true}, listDepths = {0, 0}, itemsMandatory = {false, false})
	@GraphQLNonScalar(fieldName = "addCustomEquipment", graphQLTypeSimpleName = "VehicleStateMutationResult", javaClass = VehicleStateMutationResult.class)
	VehicleStateMutationResult addCustomEquipment;


	@JsonProperty("changeEquipment")
	@GraphQLInputParameters(names = {"inventoryId", "change"}, types = {"String", "EquipmentChangeInput"}, mandatories = {true, true}, listDepths = {0, 0}, itemsMandatory = {false, false})
	@GraphQLNonScalar(fieldName = "changeEquipment", graphQLTypeSimpleName = "VehicleStateMutationResult", javaClass = VehicleStateMutationResult.class)
	VehicleStateMutationResult changeEquipment;


	@JsonProperty("removeCatalogEquipment")
	@GraphQLInputParameters(names = {"inventoryId", "optionCode"}, types = {"String", "String"}, mandatories = {true, true}, listDepths = {0, 0}, itemsMandatory = {false, false})
	@GraphQLNonScalar(fieldName = "removeCatalogEquipment", graphQLTypeSimpleName = "VehicleStateMutationResult", javaClass = VehicleStateMutationResult.class)
	VehicleStateMutationResult removeCatalogEquipment;


	@JsonProperty("removeCustomEquipment")
	@GraphQLInputParameters(names = {"inventoryId", "name"}, types = {"String", "String"}, mandatories = {true, true}, listDepths = {0, 0}, itemsMandatory = {false, false})
	@GraphQLNonScalar(fieldName = "removeCustomEquipment", graphQLTypeSimpleName = "VehicleStateMutationResult", javaClass = VehicleStateMutationResult.class)
	VehicleStateMutationResult removeCustomEquipment;


	@JsonProperty("reset")
	@GraphQLInputParameters(names = {"inventoryId", "resetWheels"}, types = {"String", "Boolean"}, mandatories = {true, false}, listDepths = {0, 0}, itemsMandatory = {false, false})
	@GraphQLNonScalar(fieldName = "reset", graphQLTypeSimpleName = "VehicleStateMutationResult", javaClass = VehicleStateMutationResult.class)
	VehicleStateMutationResult reset;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setAddCustomEquipment(VehicleStateMutationResult addCustomEquipment) {
		this.addCustomEquipment = addCustomEquipment;
	}

	public VehicleStateMutationResult getAddCustomEquipment() {
		return addCustomEquipment;
	}
		

	public void setChangeEquipment(VehicleStateMutationResult changeEquipment) {
		this.changeEquipment = changeEquipment;
	}

	public VehicleStateMutationResult getChangeEquipment() {
		return changeEquipment;
	}
		

	public void setRemoveCatalogEquipment(VehicleStateMutationResult removeCatalogEquipment) {
		this.removeCatalogEquipment = removeCatalogEquipment;
	}

	public VehicleStateMutationResult getRemoveCatalogEquipment() {
		return removeCatalogEquipment;
	}
		

	public void setRemoveCustomEquipment(VehicleStateMutationResult removeCustomEquipment) {
		this.removeCustomEquipment = removeCustomEquipment;
	}

	public VehicleStateMutationResult getRemoveCustomEquipment() {
		return removeCustomEquipment;
	}
		

	public void setReset(VehicleStateMutationResult reset) {
		this.reset = reset;
	}

	public VehicleStateMutationResult getReset() {
		return reset;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "EquipmentMutations {"
				+ "addCustomEquipment: " + addCustomEquipment
				+ ", "
				+ "changeEquipment: " + changeEquipment
				+ ", "
				+ "removeCatalogEquipment: " + removeCatalogEquipment
				+ ", "
				+ "removeCustomEquipment: " + removeCustomEquipment
				+ ", "
				+ "reset: " + reset
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private VehicleStateMutationResult addCustomEquipment;
		private VehicleStateMutationResult changeEquipment;
		private VehicleStateMutationResult removeCatalogEquipment;
		private VehicleStateMutationResult removeCustomEquipment;
		private VehicleStateMutationResult reset;

		public Builder withAddCustomEquipment(VehicleStateMutationResult addCustomEquipment) {
			this.addCustomEquipment = addCustomEquipment;
			return this;
		}
		public Builder withChangeEquipment(VehicleStateMutationResult changeEquipment) {
			this.changeEquipment = changeEquipment;
			return this;
		}
		public Builder withRemoveCatalogEquipment(VehicleStateMutationResult removeCatalogEquipment) {
			this.removeCatalogEquipment = removeCatalogEquipment;
			return this;
		}
		public Builder withRemoveCustomEquipment(VehicleStateMutationResult removeCustomEquipment) {
			this.removeCustomEquipment = removeCustomEquipment;
			return this;
		}
		public Builder withReset(VehicleStateMutationResult reset) {
			this.reset = reset;
			return this;
		}

		public EquipmentMutations build() {
			EquipmentMutations _object = new EquipmentMutations();
			_object.setAddCustomEquipment(addCustomEquipment);
			_object.setChangeEquipment(changeEquipment);
			_object.setRemoveCatalogEquipment(removeCatalogEquipment);
			_object.setRemoveCustomEquipment(removeCustomEquipment);
			_object.setReset(reset);
			_object.set__typename("EquipmentMutations");
			return _object;
		}
	}
}
