/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import cn.zy.client.util.CustomJacksonDeserializers;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLInterfaceType;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLScalar;
import java.util.List;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@JsonTypeInfo(use = Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "__typename", visible = true)
@JsonSubTypes({ @Type(value = FactoryVehicleEquipmentInformation.class, name = "FactoryVehicleEquipmentInformation"), @Type(value = VehicleStateEquipmentInformation.class, name = "VehicleStateEquipmentInformation") })
@GraphQLInterfaceType("EquipmentInformation")
@SuppressWarnings("unused")
public interface EquipmentInformation  {

	@JsonProperty("options")
	@GraphQLNonScalar(fieldName = "options", graphQLTypeSimpleName = "EquipmentOptions", javaClass = EquipmentOptions.class)
	public void setOptions(EquipmentOptions options);

	@JsonProperty("options")
	@GraphQLNonScalar(fieldName = "options", graphQLTypeSimpleName = "EquipmentOptions", javaClass = EquipmentOptions.class)
	public EquipmentOptions getOptions();

	@JsonProperty("packages")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListEquipmentPackage.class)
	@GraphQLNonScalar(fieldName = "packages", graphQLTypeSimpleName = "EquipmentPackage", javaClass = EquipmentPackage.class)
	public void setPackages(List<EquipmentPackage> packages);

	@JsonProperty("packages")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListEquipmentPackage.class)
	@GraphQLNonScalar(fieldName = "packages", graphQLTypeSimpleName = "EquipmentPackage", javaClass = EquipmentPackage.class)
	public List<EquipmentPackage> getPackages();

	@JsonProperty("categories")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListEquipmentCategoryDetails.class)
	@GraphQLNonScalar(fieldName = "categories", graphQLTypeSimpleName = "EquipmentCategoryDetails", javaClass = EquipmentCategoryDetails.class)
	public void setCategories(List<EquipmentCategoryDetails> categories);

	@JsonProperty("categories")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListEquipmentCategoryDetails.class)
	@GraphQLNonScalar(fieldName = "categories", graphQLTypeSimpleName = "EquipmentCategoryDetails", javaClass = EquipmentCategoryDetails.class)
	public List<EquipmentCategoryDetails> getCategories();

	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	public void set__typename(String __typename);

	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	public String get__typename();

	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue);

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias);

}
