/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import cn.zy.client.util.CustomJacksonDeserializers;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;
import java.util.List;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("FactoryVehicleEquipmentOptions")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class FactoryVehicleEquipmentOptions 
	implements EquipmentOptions{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public FactoryVehicleEquipmentOptions(){
		// No action
	}

	@JsonProperty("wheels")
	@GraphQLNonScalar(fieldName = "wheels", graphQLTypeSimpleName = "FactoryVehicleWheels", javaClass = FactoryVehicleWheels.class)
	FactoryVehicleWheels wheels;


	@JsonProperty("list")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListFactoryVehicleEquipment.class)
	@GraphQLInputParameters(names = {"filter"}, types = {"FactoryVehicleEquipmentOptionsFilterInput"}, mandatories = {false}, listDepths = {0}, itemsMandatory = {false})
	@GraphQLNonScalar(fieldName = "list", graphQLTypeSimpleName = "FactoryVehicleEquipment", javaClass = FactoryVehicleEquipment.class)
	List<FactoryVehicleEquipment> list;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;




	/**
	 */
	@Override
	public void setWheels(Wheels wheels) {
		if (wheels == null || wheels instanceof FactoryVehicleWheels) {
			this.wheels = (FactoryVehicleWheels) wheels;
		} else {
			throw new IllegalArgumentException("The given wheels should be an instance of cn.zy.client.FactoryVehicleWheels, but is an instance of "
					+ wheels.getClass().getName());
		}
	}
 

	/** 
	 * As the type declared in the class is not inherited from one of the implemented interfaces, we need a dedicated setter.
	 * 
	 * @param
	 */
	public void setWheels(FactoryVehicleWheels wheels) {
		this.wheels = wheels;
	}

	/**
	 */
	@Override
	public FactoryVehicleWheels getWheels() {
		return wheels;
	}

	public void setList(List<FactoryVehicleEquipment> list) {
		this.list = list;
	}

	public List<FactoryVehicleEquipment> getList() {
		return list;
	}
		


	/**
	 */
	@Override
	public void set__typename(String __typename) {
		if (__typename == null || __typename instanceof String) {
			this.__typename = (String) __typename;
		} else {
			throw new IllegalArgumentException("The given __typename should be an instance of java.lang.String, but is an instance of "
					+ __typename.getClass().getName());
		}
	}
 

	/**
	 */
	@Override
	public String get__typename() {
		return __typename;
	}

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "FactoryVehicleEquipmentOptions {"
				+ "wheels: " + wheels
				+ ", "
				+ "list: " + list
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private FactoryVehicleWheels wheels;
		private List<FactoryVehicleEquipment> list;

		public Builder withWheels(FactoryVehicleWheels wheels) {
			this.wheels = wheels;
			return this;
		}
		public Builder withList(List<FactoryVehicleEquipment> list) {
			this.list = list;
			return this;
		}

		public FactoryVehicleEquipmentOptions build() {
			FactoryVehicleEquipmentOptions _object = new FactoryVehicleEquipmentOptions();
			_object.setWheels(wheels);
			_object.setList(list);
			_object.set__typename("FactoryVehicleEquipmentOptions");
			return _object;
		}
	}
}
