/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("FormattedSwissEnergyEfficiency")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class FormattedSwissEnergyEfficiency 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public FormattedSwissEnergyEfficiency(){
		// No action
	}

	@JsonProperty("co2Emission")
	@GraphQLNonScalar(fieldName = "co2Emission", graphQLTypeSimpleName = "FormattedSwissEnergyEfficiencyLabeledValue", javaClass = FormattedSwissEnergyEfficiencyLabeledValue.class)
	FormattedSwissEnergyEfficiencyLabeledValue co2Emission;


	@JsonProperty("electricityConsumption")
	@GraphQLNonScalar(fieldName = "electricityConsumption", graphQLTypeSimpleName = "FormattedSwissEnergyEfficiencyLabeledValue", javaClass = FormattedSwissEnergyEfficiencyLabeledValue.class)
	FormattedSwissEnergyEfficiencyLabeledValue electricityConsumption;


	@JsonProperty("energyEfficiencyClass")
	@GraphQLNonScalar(fieldName = "energyEfficiencyClass", graphQLTypeSimpleName = "FormattedSwissEnergyEfficiencyClass", javaClass = FormattedSwissEnergyEfficiencyClass.class)
	FormattedSwissEnergyEfficiencyClass energyEfficiencyClass;


	@JsonProperty("fuelConsumption")
	@GraphQLNonScalar(fieldName = "fuelConsumption", graphQLTypeSimpleName = "FormattedSwissEnergyEfficiencyLabeledValue", javaClass = FormattedSwissEnergyEfficiencyLabeledValue.class)
	FormattedSwissEnergyEfficiencyLabeledValue fuelConsumption;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setCo2Emission(FormattedSwissEnergyEfficiencyLabeledValue co2Emission) {
		this.co2Emission = co2Emission;
	}

	public FormattedSwissEnergyEfficiencyLabeledValue getCo2Emission() {
		return co2Emission;
	}
		

	public void setElectricityConsumption(FormattedSwissEnergyEfficiencyLabeledValue electricityConsumption) {
		this.electricityConsumption = electricityConsumption;
	}

	public FormattedSwissEnergyEfficiencyLabeledValue getElectricityConsumption() {
		return electricityConsumption;
	}
		

	public void setEnergyEfficiencyClass(FormattedSwissEnergyEfficiencyClass energyEfficiencyClass) {
		this.energyEfficiencyClass = energyEfficiencyClass;
	}

	public FormattedSwissEnergyEfficiencyClass getEnergyEfficiencyClass() {
		return energyEfficiencyClass;
	}
		

	public void setFuelConsumption(FormattedSwissEnergyEfficiencyLabeledValue fuelConsumption) {
		this.fuelConsumption = fuelConsumption;
	}

	public FormattedSwissEnergyEfficiencyLabeledValue getFuelConsumption() {
		return fuelConsumption;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "FormattedSwissEnergyEfficiency {"
				+ "co2Emission: " + co2Emission
				+ ", "
				+ "electricityConsumption: " + electricityConsumption
				+ ", "
				+ "energyEfficiencyClass: " + energyEfficiencyClass
				+ ", "
				+ "fuelConsumption: " + fuelConsumption
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private FormattedSwissEnergyEfficiencyLabeledValue co2Emission;
		private FormattedSwissEnergyEfficiencyLabeledValue electricityConsumption;
		private FormattedSwissEnergyEfficiencyClass energyEfficiencyClass;
		private FormattedSwissEnergyEfficiencyLabeledValue fuelConsumption;

		public Builder withCo2Emission(FormattedSwissEnergyEfficiencyLabeledValue co2Emission) {
			this.co2Emission = co2Emission;
			return this;
		}
		public Builder withElectricityConsumption(FormattedSwissEnergyEfficiencyLabeledValue electricityConsumption) {
			this.electricityConsumption = electricityConsumption;
			return this;
		}
		public Builder withEnergyEfficiencyClass(FormattedSwissEnergyEfficiencyClass energyEfficiencyClass) {
			this.energyEfficiencyClass = energyEfficiencyClass;
			return this;
		}
		public Builder withFuelConsumption(FormattedSwissEnergyEfficiencyLabeledValue fuelConsumption) {
			this.fuelConsumption = fuelConsumption;
			return this;
		}

		public FormattedSwissEnergyEfficiency build() {
			FormattedSwissEnergyEfficiency _object = new FormattedSwissEnergyEfficiency();
			_object.setCo2Emission(co2Emission);
			_object.setElectricityConsumption(electricityConsumption);
			_object.setEnergyEfficiencyClass(energyEfficiencyClass);
			_object.setFuelConsumption(fuelConsumption);
			_object.set__typename("FormattedSwissEnergyEfficiency");
			return _object;
		}
	}
}
