/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("FormattedFrenchEnergyEfficiency")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class FormattedFrenchEnergyEfficiency 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public FormattedFrenchEnergyEfficiency(){
		// No action
	}

	@JsonProperty("co2Emission")
	@GraphQLScalar(fieldName = "co2Emission", graphQLTypeSimpleName = "String", javaClass = String.class)
	String co2Emission;


	@JsonProperty("energyEfficiencyClass")
	@GraphQLScalar(fieldName = "energyEfficiencyClass", graphQLTypeSimpleName = "String", javaClass = String.class)
	String energyEfficiencyClass;


	@JsonProperty("energyEfficiencyClassLabel")
	@GraphQLScalar(fieldName = "energyEfficiencyClassLabel", graphQLTypeSimpleName = "String", javaClass = String.class)
	String energyEfficiencyClassLabel;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setCo2Emission(String co2Emission) {
		this.co2Emission = co2Emission;
	}

	public String getCo2Emission() {
		return co2Emission;
	}
		

	public void setEnergyEfficiencyClass(String energyEfficiencyClass) {
		this.energyEfficiencyClass = energyEfficiencyClass;
	}

	public String getEnergyEfficiencyClass() {
		return energyEfficiencyClass;
	}
		

	public void setEnergyEfficiencyClassLabel(String energyEfficiencyClassLabel) {
		this.energyEfficiencyClassLabel = energyEfficiencyClassLabel;
	}

	public String getEnergyEfficiencyClassLabel() {
		return energyEfficiencyClassLabel;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "FormattedFrenchEnergyEfficiency {"
				+ "co2Emission: " + co2Emission
				+ ", "
				+ "energyEfficiencyClass: " + energyEfficiencyClass
				+ ", "
				+ "energyEfficiencyClassLabel: " + energyEfficiencyClassLabel
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private String co2Emission;
		private String energyEfficiencyClass;
		private String energyEfficiencyClassLabel;

		public Builder withCo2Emission(String co2Emission) {
			this.co2Emission = co2Emission;
			return this;
		}
		public Builder withEnergyEfficiencyClass(String energyEfficiencyClass) {
			this.energyEfficiencyClass = energyEfficiencyClass;
			return this;
		}
		public Builder withEnergyEfficiencyClassLabel(String energyEfficiencyClassLabel) {
			this.energyEfficiencyClassLabel = energyEfficiencyClassLabel;
			return this;
		}

		public FormattedFrenchEnergyEfficiency build() {
			FormattedFrenchEnergyEfficiency _object = new FormattedFrenchEnergyEfficiency();
			_object.setCo2Emission(co2Emission);
			_object.setEnergyEfficiencyClass(energyEfficiencyClass);
			_object.setEnergyEfficiencyClassLabel(energyEfficiencyClassLabel);
			_object.set__typename("FormattedFrenchEnergyEfficiency");
			return _object;
		}
	}
}
