/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("MaxTorque")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class MaxTorque 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public MaxTorque(){
		// No action
	}

	@JsonProperty("combined")
	@GraphQLNonScalar(fieldName = "combined", graphQLTypeSimpleName = "TorqueTechnicalDataItem", javaClass = TorqueTechnicalDataItem.class)
	TorqueTechnicalDataItem combined;


	@JsonProperty("combustionEngine")
	@GraphQLNonScalar(fieldName = "combustionEngine", graphQLTypeSimpleName = "TorqueTechnicalDataItem", javaClass = TorqueTechnicalDataItem.class)
	TorqueTechnicalDataItem combustionEngine;


	@JsonProperty("combustionEngineWithOverboost")
	@GraphQLNonScalar(fieldName = "combustionEngineWithOverboost", graphQLTypeSimpleName = "TorqueTechnicalDataItem", javaClass = TorqueTechnicalDataItem.class)
	TorqueTechnicalDataItem combustionEngineWithOverboost;


	@JsonProperty("electricEngine")
	@GraphQLNonScalar(fieldName = "electricEngine", graphQLTypeSimpleName = "TorqueTechnicalDataItem", javaClass = TorqueTechnicalDataItem.class)
	TorqueTechnicalDataItem electricEngine;


	@JsonProperty("launchControl")
	@GraphQLNonScalar(fieldName = "launchControl", graphQLTypeSimpleName = "TorqueTechnicalDataItem", javaClass = TorqueTechnicalDataItem.class)
	TorqueTechnicalDataItem launchControl;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setCombined(TorqueTechnicalDataItem combined) {
		this.combined = combined;
	}

	public TorqueTechnicalDataItem getCombined() {
		return combined;
	}
		

	public void setCombustionEngine(TorqueTechnicalDataItem combustionEngine) {
		this.combustionEngine = combustionEngine;
	}

	public TorqueTechnicalDataItem getCombustionEngine() {
		return combustionEngine;
	}
		

	public void setCombustionEngineWithOverboost(TorqueTechnicalDataItem combustionEngineWithOverboost) {
		this.combustionEngineWithOverboost = combustionEngineWithOverboost;
	}

	public TorqueTechnicalDataItem getCombustionEngineWithOverboost() {
		return combustionEngineWithOverboost;
	}
		

	public void setElectricEngine(TorqueTechnicalDataItem electricEngine) {
		this.electricEngine = electricEngine;
	}

	public TorqueTechnicalDataItem getElectricEngine() {
		return electricEngine;
	}
		

	public void setLaunchControl(TorqueTechnicalDataItem launchControl) {
		this.launchControl = launchControl;
	}

	public TorqueTechnicalDataItem getLaunchControl() {
		return launchControl;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "MaxTorque {"
				+ "combined: " + combined
				+ ", "
				+ "combustionEngine: " + combustionEngine
				+ ", "
				+ "combustionEngineWithOverboost: " + combustionEngineWithOverboost
				+ ", "
				+ "electricEngine: " + electricEngine
				+ ", "
				+ "launchControl: " + launchControl
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private TorqueTechnicalDataItem combined;
		private TorqueTechnicalDataItem combustionEngine;
		private TorqueTechnicalDataItem combustionEngineWithOverboost;
		private TorqueTechnicalDataItem electricEngine;
		private TorqueTechnicalDataItem launchControl;

		public Builder withCombined(TorqueTechnicalDataItem combined) {
			this.combined = combined;
			return this;
		}
		public Builder withCombustionEngine(TorqueTechnicalDataItem combustionEngine) {
			this.combustionEngine = combustionEngine;
			return this;
		}
		public Builder withCombustionEngineWithOverboost(TorqueTechnicalDataItem combustionEngineWithOverboost) {
			this.combustionEngineWithOverboost = combustionEngineWithOverboost;
			return this;
		}
		public Builder withElectricEngine(TorqueTechnicalDataItem electricEngine) {
			this.electricEngine = electricEngine;
			return this;
		}
		public Builder withLaunchControl(TorqueTechnicalDataItem launchControl) {
			this.launchControl = launchControl;
			return this;
		}

		public MaxTorque build() {
			MaxTorque _object = new MaxTorque();
			_object.setCombined(combined);
			_object.setCombustionEngine(combustionEngine);
			_object.setCombustionEngineWithOverboost(combustionEngineWithOverboost);
			_object.setElectricEngine(electricEngine);
			_object.setLaunchControl(launchControl);
			_object.set__typename("MaxTorque");
			return _object;
		}
	}
}
