/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("PowerItem")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class PowerItem 
	implements FormattedMarketingValue{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public PowerItem(){
		// No action
	}

	@JsonProperty("bhp")
	@GraphQLNonScalar(fieldName = "bhp", graphQLTypeSimpleName = "PowerWithDisclaimer", javaClass = PowerWithDisclaimer.class)
	PowerWithDisclaimer bhp;


	@JsonProperty("formattedInMarketplace")
	@GraphQLNonScalar(fieldName = "formattedInMarketplace", graphQLTypeSimpleName = "TranslatedText", javaClass = TranslatedText.class)
	TranslatedText formattedInMarketplace;


	@JsonProperty("kwt")
	@GraphQLNonScalar(fieldName = "kwt", graphQLTypeSimpleName = "PowerWithDisclaimer", javaClass = PowerWithDisclaimer.class)
	PowerWithDisclaimer kwt;


	@JsonProperty("n12")
	@GraphQLNonScalar(fieldName = "n12", graphQLTypeSimpleName = "PowerWithDisclaimer", javaClass = PowerWithDisclaimer.class)
	PowerWithDisclaimer n12;


	@JsonProperty("name")
	@GraphQLNonScalar(fieldName = "name", graphQLTypeSimpleName = "TranslatedText", javaClass = TranslatedText.class)
	TranslatedText name;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setBhp(PowerWithDisclaimer bhp) {
		this.bhp = bhp;
	}

	public PowerWithDisclaimer getBhp() {
		return bhp;
	}
		


	/**
	 */
	@Override
	public void setFormattedInMarketplace(TranslatedText formattedInMarketplace) {
		if (formattedInMarketplace == null || formattedInMarketplace instanceof TranslatedText) {
			this.formattedInMarketplace = (TranslatedText) formattedInMarketplace;
		} else {
			throw new IllegalArgumentException("The given formattedInMarketplace should be an instance of cn.zy.client.TranslatedText, but is an instance of "
					+ formattedInMarketplace.getClass().getName());
		}
	}
 

	/**
	 */
	@Override
	public TranslatedText getFormattedInMarketplace() {
		return formattedInMarketplace;
	}

	public void setKwt(PowerWithDisclaimer kwt) {
		this.kwt = kwt;
	}

	public PowerWithDisclaimer getKwt() {
		return kwt;
	}
		

	public void setN12(PowerWithDisclaimer n12) {
		this.n12 = n12;
	}

	public PowerWithDisclaimer getN12() {
		return n12;
	}
		

	public void setName(TranslatedText name) {
		this.name = name;
	}

	public TranslatedText getName() {
		return name;
	}
		


	/**
	 */
	@Override
	public void set__typename(String __typename) {
		if (__typename == null || __typename instanceof String) {
			this.__typename = (String) __typename;
		} else {
			throw new IllegalArgumentException("The given __typename should be an instance of java.lang.String, but is an instance of "
					+ __typename.getClass().getName());
		}
	}
 

	/**
	 */
	@Override
	public String get__typename() {
		return __typename;
	}

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "PowerItem {"
				+ "bhp: " + bhp
				+ ", "
				+ "formattedInMarketplace: " + formattedInMarketplace
				+ ", "
				+ "kwt: " + kwt
				+ ", "
				+ "n12: " + n12
				+ ", "
				+ "name: " + name
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private PowerWithDisclaimer bhp;
		private TranslatedText formattedInMarketplace;
		private PowerWithDisclaimer kwt;
		private PowerWithDisclaimer n12;
		private TranslatedText name;

		public Builder withBhp(PowerWithDisclaimer bhp) {
			this.bhp = bhp;
			return this;
		}
		public Builder withFormattedInMarketplace(TranslatedText formattedInMarketplace) {
			this.formattedInMarketplace = formattedInMarketplace;
			return this;
		}
		public Builder withKwt(PowerWithDisclaimer kwt) {
			this.kwt = kwt;
			return this;
		}
		public Builder withN12(PowerWithDisclaimer n12) {
			this.n12 = n12;
			return this;
		}
		public Builder withName(TranslatedText name) {
			this.name = name;
			return this;
		}

		public PowerItem build() {
			PowerItem _object = new PowerItem();
			_object.setBhp(bhp);
			_object.setFormattedInMarketplace(formattedInMarketplace);
			_object.setKwt(kwt);
			_object.setN12(n12);
			_object.setName(name);
			_object.set__typename("PowerItem");
			return _object;
		}
	}
}
