/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import cn.zy.client.util.CustomJacksonDeserializers;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLQuery;
import com.graphql_java_generator.annotation.GraphQLScalar;
import com.graphql_java_generator.annotation.RequestType;
import java.util.List;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLQuery(name = "Query", type = RequestType.query)
@GraphQLObjectType("Query")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class Query 
 implements com.graphql_java_generator.client.GraphQLRequestObject{

	private ObjectMapper mapper = null;
	private JsonNode extensions;
	private Map<String, JsonNode> extensionsAsMap = null;

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public Query(){
		// No action
	}

	@JsonProperty("listVins")
	@GraphQLInputParameters(names = {"filter"}, types = {"VinMappingFilterInput"}, mandatories = {true}, listDepths = {0}, itemsMandatory = {false})
	@GraphQLNonScalar(fieldName = "listVins", graphQLTypeSimpleName = "VinMappingResult", javaClass = VinMappingResult.class)
	VinMappingResult listVins;


	@JsonProperty("vehicleDataForCustomerSpecifiedVehicle")
	@GraphQLInputParameters(names = {"porscheCode", "languageTags", "marketplaceCode"}, types = {"String", "String", "String"}, mandatories = {true, true, false}, listDepths = {0, 1, 0}, itemsMandatory = {false, true, false})
	@GraphQLNonScalar(fieldName = "vehicleDataForCustomerSpecifiedVehicle", graphQLTypeSimpleName = "CustomerSpecifiedVehicle", javaClass = CustomerSpecifiedVehicle.class)
	CustomerSpecifiedVehicle vehicleDataForCustomerSpecifiedVehicle;


	@JsonProperty("vehicleData")
	@GraphQLInputParameters(names = {"vin", "languageTags", "marketplaceCode"}, types = {"String", "String", "String"}, mandatories = {true, true, false}, listDepths = {0, 1, 0}, itemsMandatory = {false, true, false})
	@GraphQLNonScalar(fieldName = "vehicleData", graphQLTypeSimpleName = "FactoryVehicle", javaClass = FactoryVehicle.class)
	FactoryVehicle vehicleData;


	@JsonProperty("vehicleState")
	@GraphQLInputParameters(names = {"inventoryId", "languageTags"}, types = {"String", "String"}, mandatories = {true, true}, listDepths = {0, 1}, itemsMandatory = {false, true})
	@GraphQLNonScalar(fieldName = "vehicleState", graphQLTypeSimpleName = "VehicleState", javaClass = VehicleState.class)
	VehicleState vehicleState;


	@JsonProperty("vehicleStates")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListVehicleStateSearchResult.class)
	@GraphQLInputParameters(names = {"filter", "limit"}, types = {"VehicleStateFilterInput", "Int"}, mandatories = {true, true}, listDepths = {0, 0}, itemsMandatory = {false, false})
	@GraphQLNonScalar(fieldName = "vehicleStates", graphQLTypeSimpleName = "VehicleStateSearchResult", javaClass = VehicleStateSearchResult.class)
	List<VehicleStateSearchResult> vehicleStates;


	@JsonProperty("vin")
	@GraphQLInputParameters(names = {"inventoryId"}, types = {"String"}, mandatories = {true}, listDepths = {0}, itemsMandatory = {false})
	@GraphQLScalar(fieldName = "vin", graphQLTypeSimpleName = "String", javaClass = String.class)
	String vin;


	@JsonProperty("__schema")
	@GraphQLNonScalar(fieldName = "__schema", graphQLTypeSimpleName = "__Schema", javaClass = __Schema.class)
	__Schema __schema;


	@JsonProperty("__type")
	@GraphQLInputParameters(names = {"name"}, types = {"String"}, mandatories = {true}, listDepths = {0}, itemsMandatory = {false})
	@GraphQLNonScalar(fieldName = "__type", graphQLTypeSimpleName = "__Type", javaClass = __Type.class)
	__Type __type;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setListVins(VinMappingResult listVins) {
		this.listVins = listVins;
	}

	public VinMappingResult getListVins() {
		return listVins;
	}
		

	public void setVehicleDataForCustomerSpecifiedVehicle(CustomerSpecifiedVehicle vehicleDataForCustomerSpecifiedVehicle) {
		this.vehicleDataForCustomerSpecifiedVehicle = vehicleDataForCustomerSpecifiedVehicle;
	}

	public CustomerSpecifiedVehicle getVehicleDataForCustomerSpecifiedVehicle() {
		return vehicleDataForCustomerSpecifiedVehicle;
	}
		

	public void setVehicleData(FactoryVehicle vehicleData) {
		this.vehicleData = vehicleData;
	}

	public FactoryVehicle getVehicleData() {
		return vehicleData;
	}
		

	public void setVehicleState(VehicleState vehicleState) {
		this.vehicleState = vehicleState;
	}

	public VehicleState getVehicleState() {
		return vehicleState;
	}
		

	public void setVehicleStates(List<VehicleStateSearchResult> vehicleStates) {
		this.vehicleStates = vehicleStates;
	}

	public List<VehicleStateSearchResult> getVehicleStates() {
		return vehicleStates;
	}
		

	public void setVin(String vin) {
		this.vin = vin;
	}

	public String getVin() {
		return vin;
	}
		

	public void set__schema(__Schema __schema) {
		this.__schema = __schema;
	}

	public __Schema get__schema() {
		return __schema;
	}
		

	public void set__type(__Type __type) {
		this.__type = __type;
	}

	public __Type get__type() {
		return __type;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "Query {"
				+ "listVins: " + listVins
				+ ", "
				+ "vehicleDataForCustomerSpecifiedVehicle: " + vehicleDataForCustomerSpecifiedVehicle
				+ ", "
				+ "vehicleData: " + vehicleData
				+ ", "
				+ "vehicleState: " + vehicleState
				+ ", "
				+ "vehicleStates: " + vehicleStates
				+ ", "
				+ "vin: " + vin
				+ ", "
				+ "__schema: " + __schema
				+ ", "
				+ "__type: " + __type
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private VinMappingResult listVins;
		private CustomerSpecifiedVehicle vehicleDataForCustomerSpecifiedVehicle;
		private FactoryVehicle vehicleData;
		private VehicleState vehicleState;
		private List<VehicleStateSearchResult> vehicleStates;
		private String vin;
		private __Schema __schema;
		private __Type __type;

		public Builder withListVins(VinMappingResult listVins) {
			this.listVins = listVins;
			return this;
		}
		public Builder withVehicleDataForCustomerSpecifiedVehicle(CustomerSpecifiedVehicle vehicleDataForCustomerSpecifiedVehicle) {
			this.vehicleDataForCustomerSpecifiedVehicle = vehicleDataForCustomerSpecifiedVehicle;
			return this;
		}
		public Builder withVehicleData(FactoryVehicle vehicleData) {
			this.vehicleData = vehicleData;
			return this;
		}
		public Builder withVehicleState(VehicleState vehicleState) {
			this.vehicleState = vehicleState;
			return this;
		}
		public Builder withVehicleStates(List<VehicleStateSearchResult> vehicleStates) {
			this.vehicleStates = vehicleStates;
			return this;
		}
		public Builder withVin(String vin) {
			this.vin = vin;
			return this;
		}
		public Builder with__schema(__Schema __schema) {
			this.__schema = __schema;
			return this;
		}
		public Builder with__type(__Type __type) {
			this.__type = __type;
			return this;
		}

		public Query build() {
			Query _object = new Query();
			_object.setListVins(listVins);
			_object.setVehicleDataForCustomerSpecifiedVehicle(vehicleDataForCustomerSpecifiedVehicle);
			_object.setVehicleData(vehicleData);
			_object.setVehicleState(vehicleState);
			_object.setVehicleStates(vehicleStates);
			_object.setVin(vin);
			_object.set__schema(__schema);
			_object.set__type(__type);
			_object.set__typename("Query");
			return _object;
		}
	}
	private ObjectMapper getMapper() {
		if (mapper == null) {
			mapper = new ObjectMapper();
		}
		return mapper;
	}
	
	public JsonNode getExtensions() {
		return extensions;
	}
	
	public void setExtensions(JsonNode extensions) {
		this.extensions = extensions;
	}
	
	/**
	 * Returns the extensions as a map. The values can't be deserialized, as their type is unknown.
	 * 
	 * @return
	 */
	public Map<String, JsonNode> getExtensionsAsMap() {
		if (extensionsAsMap == null) {
			ObjectMapper mapper = new ObjectMapper();
			extensionsAsMap = mapper.convertValue(extensions, new TypeReference<Map<String, JsonNode>>() {
			});
		}
		return extensionsAsMap;
	}
	
	/**
	 * Parse the value for the given _key_, as found in the <I>extensions</I> field of the GraphQL server's response,
	 * into the given _t_ class.
	 * 
	 * @param <T>
	 * @param key
	 * @param t
	 * @return null if the key is not in the <I>extensions</I> map. Otherwise: the value for this _key_, as a _t_
	 *         instance
	 * @throws JsonProcessingException
	 *             When there is an error when converting the key's value into the _t_ class
	 */
	public <T> T getExtensionsField(String key, Class<T> t) throws JsonProcessingException {
		JsonNode node = getExtensionsAsMap().get(key);
		return (node == null) ? null : getMapper().treeToValue(node, t);
	}
}
