/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import com.graphql_java_generator.annotation.GraphQLEnumType;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLEnumType("Transmission")
@SuppressWarnings("unused")
public enum Transmission {
MANUAL, TIPTRONIC, PDK;
}
