/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import cn.zy.client.util.CustomJacksonDeserializers;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("VehiclePrice")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class VehiclePrice 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public VehiclePrice(){
		// No action
	}

	@JsonProperty("modelBasePrice")
	@GraphQLNonScalar(fieldName = "modelBasePrice", graphQLTypeSimpleName = "Price", javaClass = Price.class)
	Price modelBasePrice;


	@JsonProperty("optionPriceSum")
	@GraphQLNonScalar(fieldName = "optionPriceSum", graphQLTypeSimpleName = "Price", javaClass = Price.class)
	Price optionPriceSum;


	@JsonProperty("priceDate")
	@JsonDeserialize(using = CustomJacksonDeserializers.Date.class)
	@GraphQLScalar(fieldName = "priceDate", graphQLTypeSimpleName = "Date", javaClass = java.util.Date.class)
	java.util.Date priceDate;


	@JsonProperty("totalPrice")
	@GraphQLNonScalar(fieldName = "totalPrice", graphQLTypeSimpleName = "Price", javaClass = Price.class)
	Price totalPrice;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setModelBasePrice(Price modelBasePrice) {
		this.modelBasePrice = modelBasePrice;
	}

	public Price getModelBasePrice() {
		return modelBasePrice;
	}
		

	public void setOptionPriceSum(Price optionPriceSum) {
		this.optionPriceSum = optionPriceSum;
	}

	public Price getOptionPriceSum() {
		return optionPriceSum;
	}
		

	public void setPriceDate(java.util.Date priceDate) {
		this.priceDate = priceDate;
	}

	public java.util.Date getPriceDate() {
		return priceDate;
	}
		

	public void setTotalPrice(Price totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Price getTotalPrice() {
		return totalPrice;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "VehiclePrice {"
				+ "modelBasePrice: " + modelBasePrice
				+ ", "
				+ "optionPriceSum: " + optionPriceSum
				+ ", "
				+ "priceDate: " + priceDate
				+ ", "
				+ "totalPrice: " + totalPrice
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private Price modelBasePrice;
		private Price optionPriceSum;
		private java.util.Date priceDate;
		private Price totalPrice;

		public Builder withModelBasePrice(Price modelBasePrice) {
			this.modelBasePrice = modelBasePrice;
			return this;
		}
		public Builder withOptionPriceSum(Price optionPriceSum) {
			this.optionPriceSum = optionPriceSum;
			return this;
		}
		public Builder withPriceDate(java.util.Date priceDate) {
			this.priceDate = priceDate;
			return this;
		}
		public Builder withTotalPrice(Price totalPrice) {
			this.totalPrice = totalPrice;
			return this;
		}

		public VehiclePrice build() {
			VehiclePrice _object = new VehiclePrice();
			_object.setModelBasePrice(modelBasePrice);
			_object.setOptionPriceSum(optionPriceSum);
			_object.setPriceDate(priceDate);
			_object.setTotalPrice(totalPrice);
			_object.set__typename("VehiclePrice");
			return _object;
		}
	}
}
