/** Generated by the default template from graphql-java-generator */
package cn.zy.client;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 *
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("WltpCO2Emissions")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class WltpCO2Emissions 
{

	/**
	 * This map contains the deserialized values for the alias, as parsed from the json response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@com.graphql_java_generator.annotation.GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	public WltpCO2Emissions(){
		// No action
	}

	@JsonProperty("combined")
	@GraphQLNonScalar(fieldName = "combined", graphQLTypeSimpleName = "EmissionTechnicalDataItem", javaClass = EmissionTechnicalDataItem.class)
	EmissionTechnicalDataItem combined;


	@JsonProperty("extraHigh")
	@GraphQLNonScalar(fieldName = "extraHigh", graphQLTypeSimpleName = "EmissionTechnicalDataItem", javaClass = EmissionTechnicalDataItem.class)
	EmissionTechnicalDataItem extraHigh;


	@JsonProperty("high")
	@GraphQLNonScalar(fieldName = "high", graphQLTypeSimpleName = "EmissionTechnicalDataItem", javaClass = EmissionTechnicalDataItem.class)
	EmissionTechnicalDataItem high;


	@JsonProperty("low")
	@GraphQLNonScalar(fieldName = "low", graphQLTypeSimpleName = "EmissionTechnicalDataItem", javaClass = EmissionTechnicalDataItem.class)
	EmissionTechnicalDataItem low;


	@JsonProperty("medium")
	@GraphQLNonScalar(fieldName = "medium", graphQLTypeSimpleName = "EmissionTechnicalDataItem", javaClass = EmissionTechnicalDataItem.class)
	EmissionTechnicalDataItem medium;


	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class)
	String __typename;



	public void setCombined(EmissionTechnicalDataItem combined) {
		this.combined = combined;
	}

	public EmissionTechnicalDataItem getCombined() {
		return combined;
	}
		

	public void setExtraHigh(EmissionTechnicalDataItem extraHigh) {
		this.extraHigh = extraHigh;
	}

	public EmissionTechnicalDataItem getExtraHigh() {
		return extraHigh;
	}
		

	public void setHigh(EmissionTechnicalDataItem high) {
		this.high = high;
	}

	public EmissionTechnicalDataItem getHigh() {
		return high;
	}
		

	public void setLow(EmissionTechnicalDataItem low) {
		this.low = low;
	}

	public EmissionTechnicalDataItem getLow() {
		return low;
	}
		

	public void setMedium(EmissionTechnicalDataItem medium) {
		this.medium = medium;
	}

	public EmissionTechnicalDataItem getMedium() {
		return medium;
	}
		

	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	public String get__typename() {
		return __typename;
	}
		

 
	/**
	 * This method is called during the json deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the json.
	 * 
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis json deserialization, but this value won't be the proper custom scalar value.
	 * 
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return aliasValues.get(alias);
	}

    public String toString() {
        return "WltpCO2Emissions {"
				+ "combined: " + combined
				+ ", "
				+ "extraHigh: " + extraHigh
				+ ", "
				+ "high: " + high
				+ ", "
				+ "low: " + low
				+ ", "
				+ "medium: " + medium
				+ ", "
				+ "__typename: " + __typename
        		+ "}";
    }

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private EmissionTechnicalDataItem combined;
		private EmissionTechnicalDataItem extraHigh;
		private EmissionTechnicalDataItem high;
		private EmissionTechnicalDataItem low;
		private EmissionTechnicalDataItem medium;

		public Builder withCombined(EmissionTechnicalDataItem combined) {
			this.combined = combined;
			return this;
		}
		public Builder withExtraHigh(EmissionTechnicalDataItem extraHigh) {
			this.extraHigh = extraHigh;
			return this;
		}
		public Builder withHigh(EmissionTechnicalDataItem high) {
			this.high = high;
			return this;
		}
		public Builder withLow(EmissionTechnicalDataItem low) {
			this.low = low;
			return this;
		}
		public Builder withMedium(EmissionTechnicalDataItem medium) {
			this.medium = medium;
			return this;
		}

		public WltpCO2Emissions build() {
			WltpCO2Emissions _object = new WltpCO2Emissions();
			_object.setCombined(combined);
			_object.setExtraHigh(extraHigh);
			_object.setHigh(high);
			_object.setLow(low);
			_object.setMedium(medium);
			_object.set__typename("WltpCO2Emissions");
			return _object;
		}
	}
}
