management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

graphql:
  endpoint:
    url: http://localhost:8080/graphql

spring:
  main:
    web-application-type: none

logging:
  level:
    cn.zy: debug

