management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

spring:
  graphql:
    schema:
      printer:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/graph_test?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ${JDBC_PASS:123456}
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 10000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8080

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

